apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhab
  labels:
    app: openhab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhab
  template:
    metadata:
      labels:
        app: openhab
    spec:
      hostNetwork: true
      containers:
      - name: openhab
        image: openhab/openhab:3.2.0-debian
        env:
        - name: CRYPTO_POLICY
          value: "unlimited"
        - name: OPENHAB_HTTP_PORT
          value: "8082"
        - name: OPENHAB_HTTPS_PORT
          value: "8083"
        ports:
        - containerPort: 8082
        - containerPort: 8083
        resources:
          requests:
            cpu: 100m
            memory: 1024M
          limits:
            cpu: 1000m
            memory: 2048M
        volumeMounts:
          - name: conf
            mountPath: /openhab/conf
          - name: userdata
            mountPath: /openhab/userdata
          - name: addons
            mountPath: /openhab/addons
          - name: localtime
            mountPath: /etc/localtime
          - name: timezone
            mountPath: /etc/timezone
      volumes:
        - name: conf
          hostPath:
            path: /mnt/main/app_data/openhab/conf
        - name: userdata
          hostPath:
            path: /mnt/main/app_data/openhab/userdata
        - name: addons
          hostPath:
            path: /mnt/main/app_data/openhab/addons
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: timezone
          hostPath:
            path: /etc/timezone
            type: File

