name: deconz
services:
  deconz:
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    environment:
      DECONZ_WEB_PORT: "8380"
      DECONZ_WS_PORT: "8383"
      DECONZ_VNC_MODE: "1"
      DECONZ_VNC_PORT: "5901"
      DECONZ_NOVNC_PORT: "6080"
    image: deconzcommunity/deconz:2.29.1
    ports:
      - 8380:8380
      - 8383:8383
      - 5901:5901
      - 6080:6080
    privileged: true
    network_mode: "host"
    volumes:
      - /mnt/main/app_data/deconz:/opt/deCONZ
      - /etc/localtime:/etc/localtime
      - /dev/ttyACM0:/dev/ttyACM0